#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=98

systime_bdinfo() {
	bdt=`bdtime -g`
	if [ -n "$bdt" ]; then
		time=`echo $bdt | awk -F '-' '{print $1"-"$2"-"$3" "$4":"$5":"$6}'`
		test -n "$time" && date -s "$time"
	else
		romtime=`cat /rom/etc/.build |awk '{print $NF}'`	# get time from rom build info, set bdinfo and systime
		yy=20${romtime:0:2}
		mm=${romtime:2:2}
		dd=${romtime:4:2}
		hh=${romtime:7:2}
		mi=${romtime:9:2}
		ss=${romtime:11:2}
		time="$yy-$mm-$dd $hh:$mi:$ss"
		bdt="$yy-$mm-$dd-$hh-$mi-$ss"
		test -n "$time" && date -s "$time"
		test -n "$bdt" && bdtime -s "$bdt"
	fi
}

system_config() {
	local cfg="$1"

	local hostname conloglevel timezone

	config_get hostname "$cfg" hostname 'OpenWrt'
	echo "$hostname" > /proc/sys/kernel/hostname

	config_get conloglevel "$cfg" conloglevel
	config_get buffersize "$cfg" buffersize
	[ -z "$conloglevel" -a -z "$buffersize" ] || dmesg ${conloglevel:+-n $conloglevel} ${buffersize:+-s $buffersize}

	config_get timezone "$cfg" timezone 'UTC'
	echo "$timezone" > /tmp/TZ

	config_get zonename "$cfg" zonename
	[ -n "$zonename" ] && [ -f "/usr/share/zoneinfo/$zonename" ] && ln -s "/usr/share/zoneinfo/$zonename" /tmp/localtime

	# apply timezone to kernel
	date -k

	if [ -x /sbin/syslogd ]; then
		local args log_ip log_size log_port log_type log_file
		config_get log_ip "$cfg" log_ip 
		config_get log_size "$cfg" log_size 16
		config_get log_port "$cfg" log_port 514
		config_get log_type "$cfg" log_type circular
		config_get log_file "$cfg" log_file "/var/log/messages"
		args="${log_ip:+-L -R ${log_ip}:${log_port}} ${conloglevel:+-l $conloglevel}"
		if [ "$log_type" = "file" ]; then
			args="$args -s $log_size -O $log_file -S"
		else
			args="$args -C${log_size}"
		fi
		#service_start /sbin/syslogd $args
	fi
	if [ -x /sbin/klogd ]; then
		config_get klogconloglevel "$cfg" klogconloglevel
		args="${klogconloglevel:+-c $klogconloglevel}"
		#service_start /sbin/klogd $args
	fi
}

apply_uci_config() {
	sh -c '. /lib/functions.sh; include /lib/config; uci_apply_defaults'
}

config_lua_binfmt() {
	mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc
	echo ":lua:E::lua::/usr/bin/lua:" >/proc/sys/fs/binfmt_misc/register	
}

start() {
	config_lua_binfmt
	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	touch /var/log/wtmp
	touch /var/log/lastlog
	touch /tmp/resolv.conf.auto
	ln -sf /tmp/resolv.conf.auto /tmp/resolv.conf
	grep -q debugfs /proc/filesystems && mount -t debugfs debugfs /sys/kernel/debug
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	load_modules /etc/modules.d/*

	# allow wifi modules time to settle
	sleep 1

	/sbin/wifi detect > /tmp/wireless.tmp
	[ -s /tmp/wireless.tmp ] && {
		cat /tmp/wireless.tmp >> /etc/config/wireless
	}
	rm -f /tmp/wireless.tmp

	apply_uci_config
	config_load system
	config_foreach system_config system 
	systime_bdinfo
	
	killall -q hotplug2
	[ -x /sbin/hotplug2 ] && /sbin/hotplug2 --override --persistent \
			--set-rules-file /etc/hotplug2.rules \
			--set-coldplug-cmd /sbin/udevtrigger \
			--max-children 1 >/dev/null 2>&1 &

	# create /dev/root if it doesn't exist
	[ -e /dev/root -o -h /dev/root ] || {
		rootdev=$(awk 'BEGIN { RS=" "; FS="="; } $1 == "root" { print $2 }' < /proc/cmdline)
		[ -n "$rootdev" ] && ln -s "$rootdev" /dev/root
	}
}

stop() {
	echo "Do nothing." > /dev/null
	#service_stop /sbin/klogd
	#service_stop /sbin/syslogd
}
