#!/bin/sh
[ -f /etc/banner ] && cat /etc/banner

export STORAGE=/tmp/data
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:$STORAGE/bin:$STORAGE/sbin:$STORAGE/usr/bin:$STORAGE/usr/sbin
export LD_LIBRARY_PATH=$STORAGE/lib:$STORAGE/usr/lib
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export HOME=${HOME:-/root}
export PS1='\u@\h:\w\$ '

[ -x /bin/more ] || alias more=less
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi

[ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc

[ -x /usr/bin/arp ] || arp() { cat /proc/net/arp; }
[ -x /usr/bin/ldd ] || ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }

. /etc/profile.hiwifi

