.\" Created by Martin Quinson from the tex documentation
.\"
.TH quilt 1 "June 2, 2006" "quilt"

.SH NAME
quilt \- tool to manage series of patches

.SH SYNOPSIS
.B quilt
[-h] command [options]

.SH DESCRIPTION
Quilt is a tool to manage large sets of patches by keeping track of the
changes each patch makes. Patches can be applied, un-applied, refreshed,
etc. The key philosophical concept is that your primary output is patches.

With quilt, all work occurs within a single directory tree. Commands can be
be invoked from anywhere within the source tree. They are of the form
.B quilt cmd
similar to CVS commands. They can be abbreviated as long as the specified
part of the command is unique. All commands print some help text with
.B quilt cmd -h.

Quilt manages a stack of patches. Patches are applied incrementally on top
of the base tree plus all preceding patches. They can be pushed on top of
the stack
.RB ( "quilt push" ),
and popped off the stack
.RB ( "quilt pop" ).
Commands are available for querying the contents of the series file
.RB ( "quilt series" ,
see below), the contents of the stack
.RB ( "quilt applied" , " quilt previous" , " quilt top" ),
and the patches that are not applied at a particular moment
.RB ( "quilt next" , " quilt unapplied" ).
By default, most commands apply to the topmost patch on the stack.

Patch files are located in the
.I patches
sub-directory of the source tree (see EXAMPLE OF WORKING TREE below). The
.I QUILT_PATCHES
environment variable can be used to override this location. The
.I patches
directory may contain sub-directories. It may also be a symbolic link
instead of a directory.

A file called
.I series
contains a list of patch file names that defines the order in which patches
are applied. Unless there are means by which series files can be generated
automatically, it is usually provided along with a set of patches. In this
file, each patch file name is on a separate line. Patch files are identified
by pathnames that are relative to the
.I patches
directory; patches may be in sub-directories below this directory. Lines
in the series file that start with a hash character (#) are ignored.
You can also add a comment after each patch file name, introduced by a
space  followed by a hash character. When
quilt adds, removes, or renames patches, it automatically updates the series
file. Users of quilt can modify series files while some patches are
applied, as long as the applied patches remain in their original order.

Different series files can be used to assemble patches in different ways,
corresponding for example to different development branches.

Before a patch is applied (or ``pushed on the stack''), copies of all files
the patch modifies are saved to the
.RI .pc/ patch
directory. The patch is added to the list of currently applied patches
(.pc/applied-patches). Later when a patch is regenerated
.RB ( "quilt refresh" ),
the backup copies in
.RI .pc/ patch
are compared with the current versions of the files in the source tree using
GNU diff.

Documentation related to a patch can be put at the beginning of a patch
file.  Quilt is careful to preserve all text that precedes the actual patch
when doing a refresh. (This is limited to patches in unified format; see
.B diff
documentation).

The series file is looked up in the .pc directory, in the root of the source
tree, and in the patches directory.  The first series file that is found is
used. This may also be a symbolic link, or a file with multiple hard links.
Usually, only one series file is used for a set of patches, so the
patches sub-directory is a convenient location.

The .pc directory and its sub-directories cannot be relocated, but it can be
a symbolic link. While patches are applied to the source tree, this
directory is essential for many operations, including taking patches off the
stack
.RB ( "quilt pop" ),
and refreshing patches
.RB ( "quilt refresh" ).
Files in the .pc directory are automatically removed when they are
no longer needed, so there is no need to clean up manually.

.SH QUILT COMMANDS REFERENCE

make[5]: Entering directory `/home/hiwifi/hc5761/build_dir/host/quilt-0.48'

.IP "\fBadd\fP [-P patch] {file} ... " 4

Add one or more files to the topmost or named patch.  Files must be
added to the patch before being modified.  Files that are modified by
patches already applied on top of the specified patch cannot be added.

.IP "    -P patch" 8

Patch to add files to.


.IP "\fBannotate\fP [-P patch] {file} " 4

Print an annotated listing of the specified file showing which
patches modify which lines. Only applied patches are included.

.IP "    -P patch" 8

Stop checking for changes at the specified rather than the
topmost patch.


.IP "\fBapplied\fP [patch] " 4

Print a list of applied patches, or all patches up to and including the
specified patch in the file series.


.IP "\fBdelete\fP [-r] [--backup] [patch|-n] " 4

Remove the specified or topmost patch from the series file.  If the
patch is applied, quilt will attempt to remove it first. (Only the
topmost patch can be removed right now.)

.IP "    -n" 8
Delete the next patch after topmost, rather than the specified
or topmost patch.

.IP "    -r" 8
Remove the deleted patch file from the patches directory as well.

.IP "    --backup" 8

Rename the patch file to patch~ rather than deleting it.
Ignored if not used with `-r'.


.IP "\fBdiff\fP [-p n|-p ab] [-u|-U num|-c|-C num] [--combine patch|-z] [-R] [-P patch] [--snapshot] [--diff=utility] [--no-timestamps] [--no-index] [--sort] [--color] [file ...] " 4

Produces a diff of the specified file(s) in the topmost or specified
patch.  If no files are specified, all files that are modified are
included.

.IP "    -p n" 8
Create a -p n style patch (-p0 or -p1 are supported).

.IP "    -p ab" 8
Create a -p1 style patch, but use a/file and b/file as the
original and new filenames instead of the default
dir.orig/file and dir/file names.

.IP "    -u, -U num, -c, -C num" 8

Create a unified diff (-u, -U) with num lines of context. Create
a context diff (-c, -C) with num lines of context. The number of
context lines defaults to 3.

.IP "    --no-timestamps" 8

Do not include file timestamps in patch headers.

.IP "    --no-index" 8

Do not output Index: lines.

.IP "    -z" 8
Write to standard output the changes that have been made
relative to the topmost or specified patch.

.IP "    -R" 8
Create a reverse diff.

.IP "    -P patch" 8

Create a diff for the specified patch.  (Defaults to the topmost
patch.)

.IP "    --combine patch" 8

Create a combined diff for all patches between this patch and
the patch specified with -P. A patch name of `-' is equivalent
to specifying the first applied patch.

.IP "    --snapshot" 8

Diff against snapshot (see `quilt snapshot -h').

.IP "    --diff=utility" 8

Use the specified utility for generating the diff. The utility
is invoked with the original and new file name as arguments.

.IP "    --color[=always|auto|never]" 8

Use syntax coloring.

.IP "    --sort" 8
Sort files by their name instead of preserving the original order.


.IP "\fBedit\fP file ... " 4

Edit the specified file(s) in $EDITOR after adding it (them) to
the topmost patch.


.IP "\fBfiles\fP [-v] [-a] [-l] [--combine patch] [patch] " 4

Print the list of files that the topmost or specified patch changes.

.IP "    -a" 8
List all files in all applied patches.

.IP "    -l" 8
Add patch name to output.

.IP "    -v" 8
Verbose, more user friendly output.

.IP "    --combine patch" 8

Create a listing for all patches between this patch and
the topmost or specified patch. A patch name of `-' is
equivalent to specifying the first applied patch.



.IP "\fBfold\fP [-R] [-q] [-f] [-p strip-level] " 4

Integrate the patch read from standard input into the topmost patch:
After making sure that all files modified are part of the topmost
patch, the patch is applied with the specified strip level (which
defaults to 1).

.IP "    -R" 8
Apply patch in reverse.

.IP "    -q" 8
Quiet operation.

.IP "    -f" 8
Force apply, even if the patch has rejects. Unless in quiet mode,
apply the patch interactively: the patch utility may ask questions.

.IP "    -p strip-level" 8

The number of pathname components to strip from file names
when applying patchfile.


.IP "\fBfork\fP [new_name] " 4

Fork the topmost patch.  Forking a patch means creating a verbatim copy
of it under a new name, and use that new name instead of the original
one in the current series.  This is useful when a patch has to be
modified, but the original version of it should be preserved, e.g.
because it is used in another series, or for the history.  A typical
sequence of commands would be: fork, edit, refresh.

If new_name is missing, the name of the forked patch will be the current
patch name, followed by `-2'.  If the patch name already ends in a
dash-and-number, the number is further incremented (e.g., patch.diff,
patch-2.diff, patch-3.diff).


.IP "\fBgraph\fP [--all] [--reduce] [--lines[=num]] [--edge-labels=files] [-T ps] [patch] " 4

Generate a dot(1) directed graph showing the dependencies between
applied patches. A patch depends on another patch if both touch the same
file or, with the --lines option, if their modifications overlap. Unless
otherwise specified, the graph includes all patches that the topmost
patch depends on.
When a patch name is specified, instead of the topmost patch, create a
graph for the specified patch. The graph will include all other patches
that this patch depends on, as well as all patches that depend on this
patch.

.IP "    --all" 8
Generate a graph including all applied patches and their
dependencies. (Unapplied patches are not included.)

.IP "    --reduce" 8

Eliminate transitive edges from the graph.

.IP "    --lines[=num]" 8

Compute dependencies by looking at the lines the patches modify.
Unless a different num is specified, two lines of context are
included.

.IP "    --edge-labels=files" 8

Label graph edges with the file names that the adjacent patches
modify.

.IP "    -T ps" 8
Directly produce a PostScript output file.


.IP "\fBgrep\fP [-h|options] {pattern} " 4

Grep through the source files, recursively, skipping patches and quilt
meta-information. If no filename argument is given, the whole source
tree is searched. Please see the grep(1) manual page for options.

.IP "    -h" 8
Print this help. The grep -h option can be passed after a
double-dash (--). Search expressions that start with a dash
can be passed after a second double-dash (-- --).


.IP "\fBheader\fP [-a|-r|-e] [--backup] [--strip-diffstat] [--strip-trailing-whitespace] [patch] " 4

Print or change the header of the topmost or specified patch.

.IP "    -a, -r, -e" 8

Append to (-a) or replace (-r) the exiting patch header, or
edit (-e) the header in $EDITOR. If none of these options is
given, print the patch header.

.IP "    --strip-diffstat" 8

Strip diffstat output from the header.

.IP "    --strip-trailing-whitespace" 8

Strip trailing whitespace at the end of lines of the header.

.IP "    --backup" 8

Create a backup copy of the old version of a patch as patch~.


.IP "\fBimport\fP [-p num] [-R] [-P patch] [-f] [-d {o|a|n}] patchfile ... " 4

Import external patches.  The patches will be inserted following the
current top patch, and must be pushed after import to apply them.

.IP "    -p num" 8

Number of directory levels to strip when applying (default=1)

.IP "    -R" 8

Apply patch in reverse.

.IP "    -P patch" 8

Patch filename to use inside quilt. This option can only be
used when importing a single patch.

.IP "    -f" 8
Overwite/update existing patches.

.IP "    -d {o|a|n}" 8

When overwriting in existing patch, keep the old (o), all (a), or
new (n) patch header. If both patches include headers, this option
must be specified. This option is only effective when -f is used.


.IP "\fBmail\fP {--mbox file|--send} [-m text] [--prefix prefix] [--sender ...] [--from ...] [--to ...] [--cc ...] [--bcc ...] [--subject ...] [--reply-to message] [first_patch [last_patch]] " 4

Create mail messages from a specified range of patches, or all patches in
the series file, and either store them in a mailbox file, or send them
immediately. The editor is opened with a template for the introduction.
Please see /home/hiwifi/hc5761/staging_dir/host/share/doc/quilt-0.48/README.MAIL for details.
When specifying a range of patches, a first patch name of `-' denotes the
first, and a last patch name of `-' denotes the last patch in the series.

.IP "    -m text" 8

Text to use as the text in the introduction. When this option is
used, the editor will not be invoked, and the patches will be
processed immediately.

.IP "    --prefix prefix" 8

Use an alternate prefix in the bracketed part of the subjects
generated. Defaults to `patch'.

.IP "    --mbox file" 8

Store all messages in the specified file in mbox format. The mbox
can later be sent using formail, for example.

.IP "    --send" 8

Send the messages directly.

.IP "    --sender" 8

The envelope sender address to use. The address must be of the form
`user@domain.name'. No display name is allowed.

.IP "    --from, --subject" 8

The values for the From and Subject headers to use. If no --from
option is given, the value of the --sender option is used.

.IP "    --to, --cc, --bcc" 8

Append a recipient to the To, Cc, or Bcc header.

.IP "    --signature file" 8

Append the specified signature to messages (defaults to ~/.signature
if found; use `-' for no signature).

.IP "    --reply-to message" 8

Add the appropriate headers to reply to the specified message.


.IP "\fBnew\fP {patchname} " 4

Create a new patch with the specified file name, and insert it after the
topmost patch.

Quilt can be used in sub-directories of a source tree. It determines the
root of a source tree by searching for a patches directory above the
current working directory. Create a patches directory in the intended root
directory if quilt chooses a top-level directory that is too high up
in the directory tree.


.IP "\fBnext\fP [patch] " 4

Print the name of the next patch after the specified or topmost patch in
the series file.


.IP "\fBpatches\fP [-v] {file} " 4

Print the list of patches that modify the specified file. (Uses a
heuristic to determine which files are modified by unapplied patches.
Note that this heuristic is much slower than scanning applied patches.)

.IP "    -v" 8
Verbose, more user friendly output.


.IP "\fBpop\fP [-afRqv] [num|patch] " 4

Remove patch(es) from the stack of applied patches.  Without options,
the topmost patch is removed.  When a number is specified, remove the
specified number of patches.  When a patch name is specified, remove
patches until the specified patch end up on top of the stack.  Patch
names may include the patches/ prefix, which means that filename
completion can be used.

.IP "    -a" 8
Remove all applied patches.

.IP "    -f" 8
Force remove. The state before the patch(es) were applied will
be restored from backup files.

.IP "    -R" 8
Always verify if the patch removes cleanly; don't rely on
timestamp checks.

.IP "    -q" 8
Quiet operation.

.IP "    -v" 8
Verbose operation.


.IP "\fBprevious\fP [patch] " 4

Print the name of the previous patch before the specified or topmost
patch in the series file.


.IP "\fBpush\fP [-afqv] [--leave-rejects] [--color[=always|auto|never]] [num|patch] " 4

Apply patch(es) from the series file.  Without options, the next patch
in the series file is applied.  When a number is specified, apply the
specified number of patches.  When a patch name is specified, apply
all patches up to and including the specified patch.  Patch names may
include the patches/ prefix, which means that filename completion can
be used.

.IP "    -a" 8
Apply all patches in the series file.

.IP "    -q" 8
Quiet operation.

.IP "    -f" 8
Force apply, even if the patch has rejects. Unless in quiet mode,
apply the patch interactively: the patch utility may ask questions.

.IP "    -v" 8
Verbose operation.

.IP "    --leave-rejects" 8

Leave around the reject files patch produced, even if the patch
is not actually applied.

.IP "    --color[=always|auto|never]" 8

Use syntax coloring.


.IP "\fBrefresh\fP [-p n|-p ab] [-u|-U num|-c|-C num] [-z[new_name]] [-f] [--no-timestamps] [--no-index] [--diffstat] [--sort] [--backup] [--strip-trailing-whitespace] [patch] " 4

Refreshes the specified patch, or the topmost patch by default.
Documentation that comes before the actual patch in the patch file is
retained.

It is possible to refresh patches that are not on top.  If any patches
on top of the patch to refresh modify the same files, the script aborts
by default.  Patches can still be refreshed with -f.  In that case this
script will print a warning for each shadowed file, changes by more
recent patches will be ignored, and only changes in files that have not
been modified by any more recent patches will end up in the specified
patch.

.IP "    -p n" 8
Create a -p n style patch (-p0 or -p1 supported).

.IP "    -p ab" 8
Create a -p1 style patch, but use a/file and b/file as the
original and new filenames instead of the default
dir.orig/file and dir/file names.

.IP "    -u, -U num, -c, -C num" 8

Create a unified diff (-u, -U) with num lines of context. Create
a context diff (-c, -C) with num lines of context. The number of
context lines defaults to 3.

.IP "    -z[new_name]" 8

Create a new patch containing the changes instead of refreshing the
topmost patch. If no new name is specified, `-2' is added to the
original patch name, etc. (See the fork command.)

.IP "    --no-timestamps" 8

Do not include file timestamps in patch headers.

.IP "    --no-index" 8

Do not output Index: lines.

.IP "    --diffstat" 8

Add a diffstat section to the patch header, or replace the
existing diffstat section.

.IP "    -f" 8
Enforce refreshing of a patch that is not on top.

.IP "    --backup" 8

Create a backup copy of the old version of a patch as patch~.

.IP "    --sort" 8
Sort files by their name instead of preserving the original order.

.IP "    --strip-trailing-whitespace" 8

Strip trailing whitespace at the end of lines.


.IP "\fBrename\fP [-P patch] new_name " 4

Rename the topmost or named patch.

.IP "    -P patch" 8

Patch to rename.


.IP "\fBrevert\fP [-P patch] {file} ... " 4

Revert the changes to the topmost or named patch for the specified file(s).
Changes to files that are modified by patches on top of the specified patch
cannot be reverted.

.IP "    -P patch" 8

Revert changes in the named patch.


.IP "\fBseries\fP [-v] " 4

Print the names of all patches in the series file.

.IP "    -v" 8
Verbose, more user friendly output.


.IP "\fBsetup\fP [-d path-prefix] [-v] [--sourcedir dir] {specfile|seriesfile} " 4

Initializes a source tree from an rpm spec file or a quilt series file.

.IP "    -d" 8
Optional path prefix for the resulting source tree.

.IP "    --sourcedir" 8

Directory that contains the package sources. Defaults to `.'.

.IP "    -v" 8
Verbose debug output.


.IP "\fBsnapshot\fP [-d] " 4

Take a snapshot of the current working state.  After taking the snapshot,
the tree can be modified in the usual ways, including pushing and
popping patches.  A diff against the tree at the moment of the
snapshot can be generated with `quilt diff --snapshot'.

.IP "    -d" 8
Only remove current snapshot.


.IP "\fBtop\fP " 4

Print the name of the topmost patch on the current stack of applied
patches.


.IP "\fBunapplied\fP [patch] " 4

Print a list of patches that are not applied, or all patches that follow
the specified patch in the series file.


.IP "\fBupgrade\fP " 4

Upgrade the meta-data in a working tree from an old version of quilt to the
current version. This command is only needed when the quilt meta-data format
has changed, and the working tree still contains old-format meta-data. In that
case, quilt will request to run `quilt upgrade'.

make[5]: Leaving directory `/home/hiwifi/hc5761/build_dir/host/quilt-0.48'

.SH COMMON OPTIONS TO ALL COMMANDS

.IP "\fB--trace\fP" 8

Runs the command in bash trace mode (-x). For internal debugging.

.IP "\fB--quiltrc\fP file" 8

Use the specified configuration file instead of ~/.quiltrc (or
/etc/quilt.quiltrc if ~/.quiltrc does not exist).  See the pdf
documentation for details about its possible contents.  The
special value "-" causes quilt not to read any configuration
file.

.IP "\fB--version\fP" 8

Print the version number and exit immediately.


.SH EXAMPLE OF WORKING TREE

.fam C
.RS
.nf
work/ -+- ...
|- patches/ -+- series
|            |- patch2.diff
|            |- patch1.diff
|            +- ...
+- .pc/ -+- applied-patches
|- patch1.diff/ -+- ...
|- patch2.diff/ -+- ...
+- ...
.fi
.RE
.fam T

.SH EXAMPLE

Please refer to the pdf documentation for an example.

.SH CONFIGURATION FILE

Upon startup, quilt evaluates the file .quiltrc in the user's home
directory, or the file specified with the --quiltrc option.  This file
is a regular bash script. Default options can be passed to any command
by defining a QUILT_COMMAND_ARGS variable.  For example,
QUILT_DIFF_ARGS="--color=auto" causes the output of quilt diff to be
syntax colored when writing to a terminal.

In addition to that, quilt recognizes the following variables:

.IP QUILT_DIFF_OPTS 4

Additional options that quilt shall pass to GNU diff when generating
patches. A useful setting for C source code is "-p", which causes GNU diff
to show in the resulting patch which function a change is in.

.IP QUILT_PATCH_OPTS 4

Additional options that quilt shall pass to GNU patch when applying
patches.  For example, some versions of GNU patch support the
"--unified-reject-files" option for generating reject files in unified
diff style.

.IP QUILT_DIFFSTAT_OPTS 4

Additional options that quilt shall pass to diffstat when generating
patch statistics. For example, "-f0" can be used for an alternative output
format. Recent versions of diffstat also support alternative rounding
methods ("-r1", "-r2").

.IP QUILT_PATCHES 4

The location of patch files, defaulting to "patches".

.IP QUILT_SERIES 4

The name of the series file, defaulting to "series". Unless an absolute path
is used, the search algorithm described above applies.

.IP QUILT_PATCHES_PREFIX 4

If set to anything, quilt will prefix patch names it prints with their
directory (QUILT_PATCHES).

.IP QUILT_NO_DIFF_INDEX 4

By default, quilt prepends an Index: line to the patches it generates.
If this variable is set to anything, no line is prepended.  This is
a shortcut to adding --no-index to both QUILT_DIFF_ARGS and
QUILT_REFRESH_ARGS.

.IP QUILT_NO_DIFF_TIMESTAMP 4

By default, quilt includes timestamps in headers when generating patches.
If this variable is set to anything, no timestamp will be included.  This
is a shortcut to adding --no-timestamps to both QUILT_DIFF_ARGS and
QUILT_REFRESH_ARGS.

.IP EDITOR 4

The program to run to edit files.  If it isn't redefined in the
configuration file, $EDITOR as defined in the environment will be used.

.SH AUTHORS

Quilt started as a series of scripts written by Andrew Morton
(patch-scripts). Based on Andrew's ideas, Andreas Gruenbacher completely
rewrote the scripts, with the help of several other contributors (see
AUTHORS file in the distribution).

This man page was written by Martin Quinson, based on information found in
the pdf documentation, and in the help messages of each commands.

.SH SEE ALSO

The pdf documentation, which should be under /usr/share/doc/quilt/quilt.pdf.
Note that some distributors compress this file.
.BR zxpdf ( 1 )
can be used to display compressed pdf files.

.BR diff ( 1 ),
.BR patch ( 1 ).
